<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Products;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Products::insert([
            [
                'florists_id' => 1,
                'name' => 'Blossom Joy',
                'description' => 'Blossom Joy Bouquet is the embodiment of everlasting joy and cheerful exuberance in full bloom. This arrangement blends soft and bright colors to create a captivating visual harmony—ranging from the warm hues of peach, the vibrant glow of orange, to a refreshing touch of light blue.',
                'price' => 560000.00,
                'image' => 'uploads/products/kaninara/blossom.png',
                'flowers' => json_encode([
                    'Gerbera',
                    'Ranunculus',
                    'Anyelir (Hijau Muda)',
                    'Krisan',
                    'Anyelir (Peach)',
                    'Kosmos (Putih & Merah Muda)',
                    'Delphinium',
                    'Buttercup (Kuning)',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Luna Love Bouquet',
                'description' => 'Luna Love Bouquet menghadirkan nuansa romansa lembut di bawah sinar bulan. Kombinasi mawar merah dan putih dengan sentuhan eucalyptus menciptakan kesan elegan dan penuh kasih.',
                'price' => 1500000.00,
                'image' => 'uploads/products/kaninara/lunalove.png',
                'flowers' => json_encode([
                    'Mawar Merah',
                    'Mawar Putih',
                    'Daun Eucalyptus',
                    'Gypsophila (Baby\'s Breath)'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Scarlet Heart',
                'description' => 'Scarlet Heart Bouquet melambangkan cinta yang berapi dan penuh semangat. Mawar merah tua dipadukan dengan carnation merah muda memberi kesan berani namun lembut.',
                'price' => 890000.00,
                'image' => 'uploads/products/kaninara/scarletheart.png',
                'flowers' => json_encode([
                    'Mawar Merah',
                    'Anyelir Merah Muda',
                    'Daun Ruscus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Petal Party',
                'description' => 'Petal Party Bouquet adalah pesta warna dan keceriaan. Campuran bunga daisy, tulip, dan mawar mini menciptakan tampilan segar yang cocok untuk hadiah penuh kebahagiaan.',
                'price' => 50000.00,
                'image' => 'uploads/products/kaninara/petalparty.png',
                'flowers' => json_encode([
                    'Mawar Mini',
                    'Daisy',
                    'Tulip',
                    'Krisan Hijau'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Bloomette',
                'description' => 'Bloomette Bouquet menampilkan pesona bunga kecil berwarna pastel dengan gaya modern. Cocok untuk hadiah ringan namun berkesan.',
                'price' => 30000.00,
                'image' => 'uploads/products/kaninara/bloomette.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Krisan Putih',
                    'Lavender',
                    'Eucalyptus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Petit Bliss',
                'description' => 'Petit Bliss Bouquet adalah buket mungil dengan sentuhan warna lembut yang menenangkan. Bunga mawar pastel dan baby’s breath menghadirkan keindahan sederhana.',
                'price' => 45000.00,
                'image' => 'uploads/products/kaninara/petitbliss.png',
                'flowers' => json_encode([
                    'Mawar Peach',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Pure Amour',
                'description' => 'Pure Amour Bouquet adalah simbol cinta yang tulus dan suci. Kombinasi bunga putih dan pink lembut menjadikannya pilihan ideal untuk momen spesial.',
                'price' => 65000.00,
                'image' => 'uploads/products/kaninara/pureamour.png',
                'flowers' => json_encode([
                    'Mawar Putih',
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Eucalyptus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Luna Belle',
                'description' => 'Luna Belle Bouquet memancarkan keanggunan malam yang lembut. Perpaduan mawar merah muda dan lily putih memberikan nuansa feminin yang menawan.',
                'price' => 200000.00,
                'image' => 'uploads/products/kaninara/lunabelle.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Eucalyptus',
                    'Daun Ruscus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Warm Embrace',
                'description' => 'Warm Embrace Bouquet menghadirkan kehangatan kasih dengan kombinasi mawar merah dan putih yang elegan, sempurna untuk mengungkapkan cinta dan perhatian.',
                'price' => 55000.00,
                'image' => 'uploads/products/kaninara/warmembrace.png',
                'flowers' => json_encode([
                    'Mawar Merah',
                    'Mawar Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Sugar Fields',
                'description' => 'Sugar Fields Bouquet adalah buket manis dengan warna pastel yang menenangkan. Kombinasi bunga mawar dan hydrangea putih memberikan kesan lembut dan romantis.',
                'price' => 270000.00,
                'image' => 'uploads/products/ren/sugarfields.png',
                'flowers' => json_encode([
                    'Mawar Putih',
                    'Mawar Peach',
                    'Hydrangea Putih'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Honey Dusk',
                'description' => 'Honey Dusk Bouquet terinspirasi dari kehangatan matahari sore. Warna kuning keemasan bunga sunflower dan tulip memberi energi positif dan semangat.',
                'price' => 230000.00,
                'image' => 'uploads/products/ren/honeydusk.png',
                'flowers' => json_encode([
                    'Bunga Matahari',
                    'Tulip Kuning',
                    'Solidago',
                    'Dedauan Hijau'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Moonveil',
                'description' => 'Moonveil Bouquet menampilkan kombinasi lembut mawar putih dan lavender yang mencerminkan ketenangan malam. Cocok untuk ucapan selamat dan doa tulus.',
                'price' => 190000.00,
                'image' => 'uploads/products/ren/moonveil.png',
                'flowers' => json_encode([
                    'Mawar Putih',
                    'Lavender',
                    'Silver Dust Leaf'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Morning Dew',
                'description' => 'Morning Dew Bouquet menghadirkan kesegaran pagi dengan paduan lily putih dan hydrangea biru, mencerminkan awal hari yang cerah dan penuh harapan.',
                'price' => 520000.00,
                'image' => 'uploads/products/ren/morningdew.png',
                'flowers' => json_encode([
                    'Lili Putih',
                    'Hydrangea Biru',
                    'Eucalyptus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Daisy Whispers',
                'description' => 'Daisy Whispers Bouquet adalah simbol keceriaan dan ketulusan. Kombinasi bunga daisy putih dan kuning membuat siapa pun tersenyum melihatnya.',
                'price' => 130000.00,
                'image' => 'uploads/products/ren/daisywhispers.png',
                'flowers' => json_encode([
                    'Daisy Putih',
                    'Daisy Kuning',
                    'Krisan Kancing Hijau'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Violet Mist',
                'description' => 'Violet Mist Bouquet menghadirkan nuansa misterius dan elegan melalui kombinasi bunga ungu lembut dan putih. Ideal untuk hadiah elegan.',
                'price' => 845000.00,
                'image' => 'uploads/products/ren/violetmist.png',
                'flowers' => json_encode([
                    'Mawar Ungu',
                    'Lili Putih',
                    'Lavender',
                    'Eucalyptus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Roselia Grace',
                'description' => 'Roselia Grace Bouquet menghadirkan keanggunan klasik dengan mawar merah muda dan lily putih. Buket ini memancarkan keindahan yang tenang dan berkelas.',
                'price' => 665000.00,
                'image' => 'uploads/products/ren/roseliagrace.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Daun Eucalyptus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Midnight Bloom',
                'description' => 'Midnight Bloom Bouquet menghadirkan perpaduan gelap dan mewah dengan bunga ungu tua dan biru kehitaman, cocok untuk acara malam yang elegan.',
                'price' => 150000.00,
                'image' => 'uploads/products/ren/midnightbloom.png',
                'flowers' => json_encode([
                    'Tulip Ungu Tua',
                    'Iris Biru',
                    'Eucalyptus'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Lilac Haze',
                'description' => 'Lilac Haze Bouquet menampilkan bunga lilac lembut dengan aroma manis dan warna pastel yang menenangkan, menciptakan suasana romantis nan tenang.',
                'price' => 200000.00,
                'image' => 'uploads/products/ren/lilachaze.png',
                'flowers' => json_encode([
                    'Lilac',
                    'Lavender',
                    'Mawar Putih'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Golden Verse',
                'description' => 'Golden Verse Bouquet bersinar dengan pesona keemasan. Kombinasi sunflower, tulip kuning, dan gerbera menghadirkan nuansa ceria dan optimis, sempurna untuk ucapan selamat atau semangat baru.',
                'price' => 100000.00,
                'image' => 'uploads/products/kaning/goldenverse.png',
                'flowers' => json_encode([
                    'Bunga Matahari',
                    'Tulip Kuning',
                    'Gerbera Kuning',
                    'Solidago (Goldenrod)',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Velvet Promise',
                'description' => 'Velvet Promise Bouquet memancarkan keanggunan mewah dengan kombinasi mawar merah marun dan lily putih, melambangkan cinta dan janji yang tulus.',
                'price' => 350000.00,
                'image' => 'uploads/products/kaning/velvetpromise.png',
                'flowers' => json_encode([
                    'Mawar Red Velvet',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Mocha Petals',
                'description' => 'Mocha Petals Bouquet menghadirkan nuansa hangat dan lembut. Campuran bunga dengan warna coklat keemasan dan krim menciptakan kesan elegan dan modern.',
                'price' => 50000.00,
                'image' => 'uploads/products/kaning/mochapetals.png',
                'flowers' => json_encode([
                    'Mawar Champagne',
                    'Anyelir Beige',
                    'Krisan Coklat',
                    'Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Lilac Veil',
                'description' => 'Lilac Veil Bouquet tampil anggun dengan nuansa ungu lembut dan putih. Cocok untuk momen istimewa yang memancarkan kedamaian dan keindahan.',
                'price' => 120000.00,
                'image' => 'uploads/products/kaning/lilacveil.png',
                'flowers' => json_encode([
                    'Lilac',
                    'Lavender',
                    'Mawar Putih',
                    'Silver Dust Leaf',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Rosewood Charm',
                'description' => 'Rosewood Charm Bouquet menampilkan pesona klasik dengan perpaduan mawar merah muda dan daun kehijauan yang menenangkan.',
                'price' => 75000.00,
                'image' => 'uploads/products/kaning/rosewoodcharm.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Anyelir Peach',
                    'Daun Eucalyptus',
                    'Ruscus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Ivory Whisper',
                'description' => 'Ivory Whisper Bouquet mencerminkan kelembutan dan ketulusan. Kombinasi bunga putih dan krim menghadirkan kesan murni dan elegan.',
                'price' => 85000.00,
                'image' => 'uploads/products/kaning/ivorywhisper.png',
                'flowers' => json_encode([
                    'Mawar Putih',
                    'Tulip Krim',
                    'Gypsophila (Baby\'s Breath)',
                    'Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Evergreen Tale',
                'description' => 'Evergreen Tale Bouquet menggabungkan warna hijau alami dengan bunga putih untuk menghadirkan kesan segar, natural, dan penuh kehidupan.',
                'price' => 200000.00,
                'image' => 'uploads/products/kaning/evergreentale.png',
                'flowers' => json_encode([
                    'Lili Putih',
                    'Hydrangea Hijau',
                    'Daun Pakis',
                    'Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Blush Haven',
                'description' => 'Blush Haven Bouquet menghadirkan kombinasi bunga lembut bernuansa pink pastel yang romantis dan menenangkan.',
                'price' => 95000.00,
                'image' => 'uploads/products/kaning/blushhaven.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Peony Blush',
                    'Daisy Putih',
                    'Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Tulip Tales',
                'description' => 'Tulip Tales Bouquet adalah kisah elegan dari bunga tulip berbagai warna yang menggambarkan cinta dan harapan baru.',
                'price' => 140000.00,
                'image' => 'uploads/products/beverly/tuliptales.png',
                'flowers' => json_encode([
                    'Pink Tulip',
                    'Yellow Tulip',
                    'White Tulip',
                    'Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Sun Dancer',
                'description' => 'Sun Dancer Bouquet penuh energi dan keceriaan. Perpaduan sunflower dan gerbera kuning memberikan semangat positif pada setiap momen.',
                'price' => 115000.00,
                'image' => 'uploads/products/beverly/sundancer.png',
                'flowers' => json_encode([
                    'Sunflower',
                    'Yellow Gerbera Daisy',
                    'Solidago',
                    'Green Leaves',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Blush Reverie',
                'description' => 'Blush Reverie Bouquet membawa suasana mimpi romantis dengan bunga berwarna lembut dan aroma manis yang menenangkan.',
                'price' => 90000.00,
                'image' => 'uploads/products/beverly/blushreverie.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'White Chrysanthemum',
                    'Peach Carnation',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Vanilla Bloom',
                'description' => 'Vanilla Bloom Bouquet menonjolkan keindahan klasik bunga putih dan krem yang sederhana namun elegan.',
                'price' => 300000.00,
                'image' => 'uploads/products/beverly/vanillabloom.png',
                'flowers' => json_encode([
                    'Lili Putih',
                    'Cream Rose',
                    'Eucalyptus',
                    'Fern Leaf',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Golden Serenade',
                'description' => 'Golden Serenade Bouquet memadukan warna kuning dan oranye hangat, menggambarkan kehangatan cinta dan persahabatan sejati.',
                'price' => 250000.00,
                'image' => 'uploads/products/beverly/goldenserenade.png',
                'flowers' => json_encode([
                    'Yellow Rose',
                    'Orange Tulip',
                    'Sunflower',
                    'Solidago',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Rosy Rhapsody',
                'description' => 'Rosy Rhapsody Bouquet menampilkan kemewahan mawar merah muda dan putih dalam harmoni indah yang menawan.',
                'price' => 1450000.00,
                'image' => 'uploads/products/beverly/rosyrhapsody.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Mawar Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Sunlit Grace',
                'description' => 'Sunlit Grace Bouquet bercahaya lembut seperti sinar matahari pagi. Kombinasi bunga kuning dan putih memberikan kesan hangat dan damai.',
                'price' => 125000.00,
                'image' => 'uploads/products/beverly/sunlitgrace.png',
                'flowers' => json_encode([
                    'Mawar Kuning',
                    'Lili Putih',
                    'Solidago',
                    'Dedauan Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Apricot Whisper',
                'description' => 'Apricot Whisper Bouquet menghadirkan kelembutan warna peach dan krim yang elegan, sempurna untuk hadiah penuh cinta dan ketulusan.',
                'price' => 195000.00,
                'image' => 'uploads/products/beverly/apricotwhisper.png',
                'flowers' => json_encode([
                    'Mawar Peach',
                    'Tulip Krim',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Honey Bloom',
                'description' => 'Honey Bloom Bouquet menggabungkan warna keemasan dan krem untuk menciptakan suasana hangat dan menenangkan seperti cahaya sore hari.',
                'price' => 95000.00,
                'image' => 'uploads/products/beverly/honeybloom.png',
                'flowers' => json_encode([
                    'Bunga Matahari',
                    'Tulip Kuning',
                    'Anyelir Krim',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5-6 belum
            [
                'florists_id' => 7,
                'name' => 'Arctic Bloom',
                'description' => 'Eternal Love Bouquet adalah ekspresi abadi dari kasih mendalam dan komitmen yang tak tergoyahkan. Buket elegan ini menampilkan mawar merah dan putih klasik, melambangkan cinta yang penuh gairah dan pengabdian murni, dilengkapi daun eucalyptus untuk menambah keindahan alami.',
                'price' => 256000.00,
                'image' => 'uploads/products/jardinelle/arcticbloom.png',
                'flowers' => json_encode([
                    'Mawar Merah',
                    'Mawar Putih',
                    'Daun Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Violet Grace',
                'description' => 'Sunshine Delight Bouquet adalah perayaan yang memancarkan kehangatan, kebahagiaan, dan energi hidup yang ceria. Buket ini memadukan warna kuning cerah dari bunga matahari, gerbera daisy yang ceria, dan tulip kuning, menciptakan tampilan yang hidup dan menyenangkan untuk setiap kesempatan.',
                'price' => 60000.00,
                'image' => 'uploads/products/jardinelle/violetgrace.png',
                'flowers' => json_encode([
                    'Bunga Matahari',
                    'Gerbera Kuning',
                    'Tulip Kuning',
                    'Solidago (Goldenrod)',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Moonlight Whisper',
                'description' => 'Elegance in Bloom Bouquet adalah rangkaian bunga yang anggun dan memancarkan keindahan abadi. Memadukan mawar merah muda lembut, lily putih yang halus, dan dedaunan hijau yang subur, buket ini sempurna untuk menyampaikan rasa hormat dan kekaguman pada momen spesial.',
                'price' => 490000.00,
                'image' => 'uploads/products/jardinelle/moonlightwhisper.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Slate Rose',
                'description' => 'Sunshine Delight Bouquet menghadirkan kombinasi warna cerah yang memancarkan kebahagiaan. Buket ini menampilkan bunga matahari, gerbera daisy kuning, tulip kuning, dan dedaunan hijau, sempurna untuk momen yang menyenangkan.',
                'price' => 100000.00,
                'image' => 'uploads/products/jardinelle/slaterose.png',
                'flowers' => json_encode([
                    'Sunflower',
                    'Gerbera Daisy (Yellow)',
                    'Yellow Tulip',
                    'Solidago (Goldenrod)',
                    'Greenery Filler',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Golden Soft Peach',
                'description' => 'Elegance in Bloom Bouquet adalah rangkaian bunga yang anggun dan memancarkan pesona klasik. Buket ini memadukan mawar merah muda lembut, lily putih, baby\'s breath, dan dedaunan eucalyptus untuk kesan yang harmonis.',
                'price' => 87000.00,
                'image' => 'uploads/products/jardinelle/goldensoft.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Blush Muse',
                'description' => 'Romance in Bloom Bouquet adalah ekspresi kasih yang hangat dan penuh gairah. Buket ini memadukan mawar merah dan putih, baby\'s breath (gypsophila), serta daun eucalyptus yang menambah nuansa romantis.',
                'price' => 75000.00,
                'image' => 'uploads/products/jardinelle/blushmuse.png',
                'flowers' => json_encode([
                    'Anggrek (Orchid)',
                    'Mawar Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Rosé Allure',
                'description' => 'Elegance in Bloom Bouquet menampilkan perpaduan lembut antara mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus, sempurna untuk menyampaikan rasa hormat dan kekaguman.',
                'price' => 95000.00,
                'image' => 'uploads/products/jardinelle/roseallure.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Crimson Royale',
                'description' => 'Romance in Bloom Bouquet adalah simbol cinta dan pengabdian yang mendalam. Buket ini menampilkan mawar merah dan putih, baby\'s breath (gypsophila), dan daun eucalyptus untuk menambah kesan romantis.',
                'price' => 175000.00,
                'image' => 'uploads/products/jardinelle/crimsonroyale.png',
                'flowers' => json_encode([
                    'Mawar Merah',
                    'Mawar Putih',
                    'Gypsophila (Gypsophila)',
                    'Daun Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Lilac Serenity',
                'description' => 'Romance in Bloom Bouquet menghadirkan kombinasi lembut mawar merah dan putih, baby\'s breath, serta daun eucalyptus, ideal untuk momen yang penuh kasih.',
                'price' => 90000.00,
                'image' => 'uploads/products/jardinelle/lilacserenity.png',
                'flowers' => json_encode([
                    'Red Rose',
                    'White Rose',
                    'Baby\'s Breath (Gypsophila)',
                    'Eucalyptus Leaves',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Florist ID 8
            [
                'florists_id' => 8,
                'name' => 'Daisy Delight',
                'description' => 'Elegance in Bloom Bouquet adalah rangkaian anggun yang memadukan mawar merah muda, lily putih, baby\'s breath, dan dedaunan hijau untuk momen istimewa.',
                'price' => 90000.00,
                'image' => 'uploads/products/florya/daisydelight.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Orchid Charm',
                'description' => 'Romance in Bloom Bouquet menampilkan keindahan abadi dengan mawar merah dan putih, baby\'s breath (gypsophila), dan daun eucalyptus yang menambah kesan elegan.',
                'price' => 1250000.00,
                'image' => 'uploads/products/florya/orchidcharm.png',
                'flowers' => json_encode([
                    'Red Rose',
                    'White Rose',
                    'Baby\'s Breath (Gypsophila)',
                    'Eucalyptus Leaves',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Golden Meadow',
                'description' => 'Elegance in Bloom Bouquet memadukan mawar merah muda, lily putih, baby\'s breath, dan daun eucalyptus, menciptakan buket yang menawan untuk momen spesial.',
                'price' => 370000.00,
                'image' => 'uploads/products/florya/goldenmeadow.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Rose Blush',
                'description' => 'Romance in Bloom Bouquet adalah ekspresi cinta dan pengabdian. Buket ini memadukan mawar merah dan putih, baby\'s breath, dan daun eucalyptus untuk nuansa romantis.',
                'price' => 130000.00,
                'image' => 'uploads/products/florya/roseblush.png',
                'flowers' => json_encode([
                    'Mawar Merah',
                    'Mawar Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Pure Serenity',
                'description' => 'Romance in Bloom Bouquet memadukan mawar merah dan putih, baby\'s breath, dan daun eucalyptus, ideal untuk momen yang damai dan romantis.',
                'price' => 87000.00,
                'image' => 'uploads/products/florya/pureserenity.png',
                'flowers' => json_encode([
                    'Mawar Putih',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Pink Whisper',
                'description' => 'Elegance in Bloom Bouquet menampilkan perpaduan lembut antara mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus untuk kesan elegan.',
                'price' => 135000.00,
                'image' => 'uploads/products/florya/pinkwhisper.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Lavender Grace',
                'description' => 'Elegance in Bloom Bouquet memadukan mawar merah muda, lily putih, baby\'s breath, dan daun eucalyptus untuk buket yang anggun dan menawan.',
                'price' => 95000.00,
                'image' => 'uploads/products/florya/lavendergrace.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Sunny Bloom',
                'description' => 'Elegance in Bloom Bouquet menghadirkan buket yang mewah dan cerah dengan perpaduan mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus.',
                'price' => 1200000.00,
                'image' => 'uploads/products/florya/sunnybloom.png',
                'flowers' => json_encode([
                    'Mawar Merah Muda',
                    'Lili Putih',
                    'Gypsophila (Baby\'s Breath)',
                    'Daun Eucalyptus',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Pearl Whisper',
                'description' => 'Elegance in Bloom Bouquet adalah rangkaian lembut yang memadukan mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus untuk momen istimewa.',
                'price' => 145000.00,
                'image' => 'uploads/products/florya/pearlwhisper.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Baby\'s Breath',
                    'Eucalyptus Leaves',
                    'Isian Hijau',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 9-11 belum
            [
                'florists_id' => 12,
                'name' => 'Rosy Whisper',
                'description' => 'Elegance in Bloom Bouquet adalah rangkaian bunga yang anggun dan memancarkan keindahan abadi. Buket ini memadukan mawar merah muda lembut, lily putih, baby\'s breath, dan dedaunan eucalyptus, sempurna untuk menyampaikan rasa hormat dan kekaguman pada setiap momen spesial.',
                'price' => 245000.00,
                'image' => 'uploads/products/lovenique/rosywhisper.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Baby\'s Breath',
                    'Eucalyptus Leaves',
                    'Greenery Filler',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Ethereal Luxe',
                'description' => 'Romance in Bloom Bouquet adalah ekspresi cinta dan gairah yang mendalam. Buket ini menampilkan mawar merah dan putih, baby\'s breath (gypsophila), dan daun eucalyptus, menciptakan kesan romantis yang menawan untuk setiap momen spesial.',
                'price' => 400000.00,
                'image' => 'uploads/products/lovenique/etherealluxe.png',
                'flowers' => json_encode([
                    'Red Rose',
                    'White Rose',
                    'Baby\'s Breath (Gypsophila)',
                    'Eucalyptus Leaves',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Velvet Romance',
                'description' => 'Elegance in Bloom Bouquet memadukan mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus untuk menciptakan buket yang anggun dan elegan, sempurna untuk momen istimewa.',
                'price' => 590000.00,
                'image' => 'uploads/products/lovenique/velvetromance.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Baby\'s Breath',
                    'Eucalyptus Leaves',
                    'Greenery Filler',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Rose I Moc',
                'description' => 'Elegance in Bloom Bouquet adalah rangkaian lembut yang memadukan mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus, cocok untuk momen penuh kasih.',
                'price' => 60000.00,
                'image' => 'uploads/products/lovenique/roseimoc.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Baby\'s Breath',
                    'Eucalyptus Leaves',
                    'Greenery Filler',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Ruby Elegance',
                'description' => 'Elegance in Bloom Bouquet menghadirkan buket yang anggun dengan mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus, ideal untuk mengekspresikan pesona dan keindahan.',
                'price' => 300000.00,
                'image' => 'uploads/products/lovenique/rubyelegance.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Baby\'s Breath',
                    'Eucalyptus Leaves',
                    'Greenery Filler',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Blushing Grace',
                'description' => 'Elegance in Bloom Bouquet adalah rangkaian bunga yang anggun dan menawan, memadukan mawar merah muda, lily putih, baby\'s breath, dan daun eucalyptus, sempurna untuk momen penuh keanggunan.',
                'price' => 175000.00,
                'image' => 'uploads/products/lovenique/blushinggrace.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Baby\'s Breath',
                    'Eucalyptus Leaves',
                    'Greenery Filler',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Sweetheart Bloom',
                'description' => 'Elegance in Bloom Bouquet menghadirkan buket lembut yang memadukan mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus, sempurna untuk mengekspresikan kelembutan dan pesona.',
                'price' => 105000.00,
                'image' => 'uploads/products/lovenique/sweetheartbloom.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Baby\'s Breath',
                    'Eucalyptus Leaves',
                    'Greenery Filler',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Crimson Desire',
                'description' => 'Elegance in Bloom Bouquet adalah buket yang memadukan mawar merah muda, lily putih, baby\'s breath, dan dedaunan eucalyptus, menciptakan kesan elegan dan memikat untuk setiap momen spesial.',
                'price' => 350000.00,
                'image' => 'uploads/products/lovenique/crimsondesire.png',
                'flowers' => json_encode([
                    'Pink Rose',
                    'White Lily',
                    'Baby\'s Breath',
                    'Eucalyptus Leaves',
                    'Greenery Filler',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
