<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Products;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Products::insert([
            [
                'florists_id' => 1,
                'name' => 'Blossom Joy',
                'description' => 'Blossom Joy Bouquet is the embodiment of everlasting joy and cheerful exuberance in full bloom. This arrangement blends soft and bright colors to create a captivating visual harmony—ranging from the warm hues of peach, the vibrant glow of orange, to a refreshing touch of light blue.',
                'price' => 560000.00,
                'image' => 'uploads/products/kaninara/blossom.png',
                'flowers' => json_encode([
                    'Gerbera Daisy',
                    'Ranunculus',
                    'Carnation (Anyelir Light Green)',
                    'Chrysanthemum',
                    'Carnation (Anyelir Peach)',
                    'Cosmos Daisy (White and Pink)',
                    'Delphinium',
                    'Buttercup Yellow',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Luna Love Bouquet',
                // 'description' => 'Eternal Love Bouquet is a timeless expression of deep affection and enduring commitment. This elegant arrangement features classic red and white roses, symbolizing passionate love and pure devotion, complemented by the soft greenery of eucalyptus leaves to enhance its natural beauty.',
                'price' => 1500000.00,
                'image' => 'uploads/products/kaninara/lunalove.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Scarlet Heart',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 890000.00,
                'image' => 'uploads/products/kaninara/scarletheart.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Petal Party',
                // 'description' => 'Eternal Love Bouquet is a timeless expression of deep affection and enduring commitment. This elegant arrangement features classic red and white roses, symbolizing passionate love and pure devotion, complemented by the soft greenery of eucalyptus leaves to enhance its natural beauty.',
                'price' => 50000.00,
                'image' => 'uploads/products/kaninara/petalparty.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Bloomette',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 30000.00,
                'image' => 'uploads/products/kaninara/bloomette.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Petit Bliss',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 45000.00,
                'image' => 'uploads/products/kaninara/petitbliss.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Pure Amour',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 65000.00,
                'image' => 'uploads/products/kaninara/pureamour.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Luna Belle',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 200000.00,
                'image' => 'uploads/products/kaninara/lunabelle.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 1,
                'name' => 'Warm Embrace',
                // 'description' => 'Romance in Bloom Bouquet is a heartfelt expression of love and passion, perfect for celebrating special moments with that special someone. This enchanting arrangement features a stunning combination of red and white roses, symbolizing deep affection and pure devotion, complemented by delicate baby\'s breath (gypsophila) and lush eucalyptus leaves to enhance its romantic allure.',
                'price' => 55000.00,
                'image' => 'uploads/products/kaninara/warmembrace.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Sugar Fields',
                // 'description' => 'Eternal Love Bouquet is a timeless expression of deep affection and enduring commitment. This arrangement features a classic combination of red and white roses, symbolizing passionate love and pure devotion, complemented by delicate white baby\'s breath to add a touch of elegance and softness.',
                'price' => 270000.00,
                'image' => 'uploads/products/ren/sugarfields.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Honey Dusk',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 230000.00,
                'image' => 'uploads/products/ren/honeydusk.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Moonveil',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 190000.00,
                'image' => 'uploads/products/ren/moonveil.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Morning Dew',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 520000.00,
                'image' => 'uploads/products/ren/morningdew.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Daisy Whispers',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 130000.00,
                'image' => 'uploads/products/ren/daisywhispers.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Violet Mist',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 845000.00,
                'image' => 'uploads/products/ren/violetmist.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Roselia Grace',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 665000.00,
                'image' => 'uploads/products/ren/roseliagrace.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Midnight Bloom',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 150000.00,
                'image' => 'uploads/products/ren/midnightbloom.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 2,
                'name' => 'Lilac Haze',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 200000.00,
                'image' => 'uploads/products/ren/lilachaze.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Amber Serenade',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 250000.00,
                'image' => 'uploads/products/kaning/amberserenade.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Golden Verse',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 100000.00,
                'image' => 'uploads/products/kaning/goldenverse.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Velvet Promise',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 350000.00,
                'image' => 'uploads/products/kaning/velvetpromise.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Mocha Petals',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 50000.00,
                'image' => 'uploads/products/kaning/mochapetals.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Lilac Veil',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 120000.00,
                'image' => 'uploads/products/kaning/lilacveil.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Rosewood Charm',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 75000.00,
                'image' => 'uploads/products/kaning/rosewoodcharm.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Ivory Whisper',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 85000.00,
                'image' => 'uploads/products/kaning/ivorywhisper.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Evergreen Tale',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 200000.00,
                'image' => 'uploads/products/kaning/evergreentale.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 3,
                'name' => 'Blush Haven',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 95000.00,
                'image' => 'uploads/products/kaning/blushhaven.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Tulip Tales',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 140000.00,
                'image' => 'uploads/products/kaning/tuliptales.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Sun Dancer',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 115000.00,
                'image' => 'uploads/products/kaning/sundancer.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Blush Reverie',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 90000.00,
                'image' => 'uploads/products/kaning/blushreverie.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Vanilla Bloom',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 300000.00,
                'image' => 'uploads/products/kaning/vanillabloom.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Golden Serenade',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 250000.00,
                'image' => 'uploads/products/kaning/goldenserenade.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Rosy Rhapsody',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 1450000.00,
                'image' => 'uploads/products/kaning/rosyrhapsody.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Sunlit Grace',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 125000.00,
                'image' => 'uploads/products/kaning/sunlitgrace.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Apricot Whisper',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 195000.00,
                'image' => 'uploads/products/kaning/apricotwhisper.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 4,
                'name' => 'Honey Bloom',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 95000.00,
                'image' => 'uploads/products/kaning/honeybloom.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5-6 belum
            [
                'florists_id' => 7,
                'name' => 'Arctic Bloom',
                // 'description' => 'Eternal Love Bouquet is a timeless expression of deep affection and enduring commitment. This elegant arrangement features classic red and white roses, symbolizing passionate love and pure devotion, complemented by the soft greenery of eucalyptus leaves to enhance its natural beauty.',
                'price' => 256000.00,
                'image' => 'uploads/products/kaninara/arcticbloom.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Violet Grace',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 60000.00,
                'image' => 'uploads/products/kaninara/violetgrace.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Moonlight Whisper',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 490000.00,
                'image' => 'uploads/products/kaninara/moonlightwhisper.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Slate Rose',
                // 'description' => 'Sunshine Delight Bouquet is a radiant celebration of warmth, happiness, and the vibrant energy of life. This arrangement combines the sunny hues of yellow sunflowers, cheerful gerbera daisies, and bright yellow tulips, creating a lively and uplifting display that brings joy to any occasion.',
                'price' => 100000.00,
                'image' => 'uploads/products/kaninara/slaterose.png',
                // 'flowers' => json_encode([
                //     'Sunflower',
                //     'Gerbera Daisy (Yellow)',
                //     'Yellow Tulip',
                //     'Solidago (Goldenrod)',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Golden Soft Peach',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 87000.00,
                'image' => 'uploads/products/kaninara/goldensoft.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath,
                //     'Eucalyptus Leaves',
                // [),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Blush Muse',
                // 'description' => 'Romance in Bloom Bouquet is a heartfelt expression of love and passion, perfect for celebrating special moments with that special someone. This enchanting arrangement features a stunning combination of red and white roses, symbolizing deep affection and pure devotion, complemented by delicate baby\'s breath (gypsophila) and lush eucalyptus leaves to enhance its romantic allure.',
                'price' => 75000.00,
                'image' => 'uploads/products/kaninara/blushmuse.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Rosé Allure',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 95000.00,
                'image' => 'uploads/products/kaninara/roseallure.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Crimson Royale',
                // 'description' => 'Romance in Bloom Bouquet is a heartfelt expression of love and passion, perfect for celebrating special moments with that special someone. This enchanting arrangement features a stunning combination of red and white roses, symbolizing deep affection and pure devotion, complemented by delicate baby\'s breath (gypsophila) and lush eucalyptus leaves to enhance its romantic allure.',
                'price' => 175000.00,
                'image' => 'uploads/products/kaninara/crimsonroyale.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 7,
                'name' => 'Lilac Serenity',
                // 'description' => 'Romance in Bloom Bouquet is a heartfelt expression of love and passion, perfect for celebrating special moments with that special someone. This enchanting arrangement features a stunning combination of red and white roses, symbolizing deep affection and pure devotion, complemented by delicate baby\'s breath (gypsophila) and lush eucalyptus leaves to enhance its romantic allure.',
                'price' => 90000.00,
                'image' => 'uploads/products/kaninara/lilacserenity.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Daisy Delight',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 90000.00,
                'image' => 'uploads/products/kaninara/daisydelight.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Orchid Charm',
                // 'description' => 'Romance in Bloom Bouquet is a heartfelt expression of love and passion, perfect for celebrating special moments with that special someone. This enchanting arrangement features a stunning combination of red and white roses, symbolizing deep affection and pure devotion, complemented by delicate baby\'s breath (gypsophila) and lush eucalyptus leaves to enhance its romantic allure.',
                'price' => 1250000.00,
                'image' => 'uploads/products/kaninara/orchidcharm.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Golden Meadow',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 370000.00,
                'image' => 'uploads/products/kaninara/goldenmeadow.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Rose Blush',
                // 'description' => 'Romance in Bloom Bouquet is a heartfelt expression of love and passion, perfect for celebrating special moments with that special someone. This enchanting arrangement features a stunning combination of red and white roses, symbolizing deep affection and pure devotion, complemented by delicate baby\'s breath (gypsophila) and lush eucalyptus leaves to enhance its romantic allure.',
                'price' => 130000.00,
                'image' => 'uploads/products/kaninara/roseblush.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Pure Serenity',
                // 'description' => 'Romance in Bloom Bouquet is a heartfelt expression of love and passion, perfect for celebrating special moments with that special someone. This enchanting arrangement features a stunning combination of red and white roses, symbolizing deep affection and pure devotion, complemented by delicate baby\'s breath (gypsophila) and lush eucalyptus leaves to enhance its romantic allure.',
                'price' => 87000.00,
                'image' => 'uploads/products/kaninara/pureserenity.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Pink Whisper',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 135000.00,
                'image' => 'uploads/products/kaninara/pinkwhisper.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Lavender Grace',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 95000.00,
                'image' => 'uploads/products/kaninara/lavendergrace.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Sunny Bloom',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 1200000.00,
                'image' => 'uploads/products/kaninara/sunnybloom.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 8,
                'name' => 'Pearl Whisper',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 145000.00,
                'image' => 'uploads/products/kaninara/pearlwhisper.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 9-11 belum
            [
                'florists_id' => 12,
                'name' => 'Rosy Whisper',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 245000.00,
                'image' => 'uploads/products/kaninara/rosywhisper.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Ethereal Luxe',
                // 'description' => 'Romance in Bloom Bouquet is a heartfelt expression of love and passion, perfect for celebrating special moments with that special someone. This enchanting arrangement features a stunning combination of red and white roses, symbolizing deep affection and pure devotion, complemented by delicate baby\'s breath (gypsophila) and lush eucalyptus leaves to enhance its romantic allure.',
                'price' => 400000.00,
                'image' => 'uploads/products/kaninara/etherealluxe.png',
                // 'flowers' => json_encode([
                //     'Red Rose',
                //     'White Rose',
                //     'Baby\'s Breath (Gypsophila)',
                //     'Eucalyptus Leaves',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Velvet Romance',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 590000.00,
                'image' => 'uploads/products/kaninara/velvetromance.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Rose I Moc',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 60000.00,
                'image' => 'uploads/products/kaninara/roseimoc.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Ruby Elegance',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 300000.00,
                'image' => 'uploads/products/kaninara/rubyelegance.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Blushing Grace',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 175000.00,
                'image' => 'uploads/products/kaninara/blushinggrace.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Sweetheart Bloom',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 105000.00,
                'image' => 'uploads/products/kaninara/sweetheartbloom.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'florists_id' => 12,
                'name' => 'Crimson Desire',
                // 'description' => 'Elegance in Bloom Bouquet is a sophisticated arrangement that exudes timeless beauty and refined charm. Featuring a harmonious blend of soft pink roses, delicate white lilies, and lush greenery, this bouquet is perfect for expressing grace and admiration on any special occasion.',
                'price' => 350000.00,
                'image' => 'uploads/products/kaninara/crimsondesire.png',
                // 'flowers' => json_encode([
                //     'Pink Rose',
                //     'White Lily',
                //     'Baby\'s Breath',
                //     'Eucalyptus Leaves',
                //     'Greenery Filler',
                // ]),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
